<a href="https://colab.research.google.com/github/Manuelard03/Caza-patos-Manuelard/blob/main/Taller_1_de_Python_Manuela_Rodr%C3%ADguez_D%C3%A1vila.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Taller 1 de Python

# Operaciones con Strings (str)

In [31]:
!zip -r mi_proyecto.zip .

  adding: .config/ (stored 0%)
  adding: .config/.last_update_check.json (deflated 24%)
  adding: .config/default_configs.db (deflated 98%)
  adding: .config/.last_opt_in_prompt.yaml (stored 0%)
  adding: .config/logs/ (stored 0%)
  adding: .config/logs/2025.02.18/ (stored 0%)
  adding: .config/logs/2025.02.18/14.19.45.014979.log (deflated 57%)
  adding: .config/logs/2025.02.18/14.19.35.876527.log (deflated 58%)
  adding: .config/logs/2025.02.18/14.19.31.209860.log (deflated 87%)
  adding: .config/logs/2025.02.18/14.19.21.783246.log (deflated 58%)
  adding: .config/logs/2025.02.18/14.19.45.736719.log (deflated 57%)
  adding: .config/logs/2025.02.18/14.18.50.396027.log (deflated 93%)
  adding: .config/config_sentinel (stored 0%)
  adding: .config/configurations/ (stored 0%)
  adding: .config/configurations/config_default (deflated 15%)
  adding: .config/gce (stored 0%)
  adding: .config/active_config (stored 0%)
  adding: .config/.last_survey_prompt.yaml (stored 0%)
  adding: .config/hi

Ejercicio 1: Dividir el string dado según los espacios, obteniendo como resultado una lista de las palabras

In [1]:
s = "The universe doesn't allow perfection"
lista_palabras = s.split()
print(lista_palabras)

['The', 'universe', "doesn't", 'allow', 'perfection']


Ejercicio 2: Dado el siguiente texto construya un programa que cuente los caracteres sin contar los espacios:

In [2]:
s = "El pasado puede doler, pero tal como yo lo veo, puedes huir o aprender de él"
caracteres_sin_espacios = len(s.replace(" ", ""))
print(caracteres_sin_espacios)

61


Ejercicio 3: Dado el siguiente texto, remplazar la palbra "apple" por "banana"

In [3]:
s = "If you wish to make an apple pie from scratch, you must first invent the universe"
s_reemplazado = s.replace("apple", "banana")
print(s_reemplazado)

If you wish to make an banana pie from scratch, you must first invent the universe


Ejercicio 4: Usar .format() para imprimir el siguiente string:

The diameter of Earth is 12742 kilometers

In [4]:
planet = "Earth"
diameter = 12742

message = "The diameter of {} is {} kilometers".format(planet, diameter)
print(message)

The diameter of Earth is 12742 kilometers


# Operaciones con Listas

Ejercicio 1: Dada la siguiente lista, obtener los primeros 3 elementos en una lista disferente (no modificar la lista original)

In [5]:
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

primeros_tres = lst[:3]
print(primeros_tres)
print(lst)

[0, 1, 2]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


Ejercicio 2: Dada la siguiente lista, obtener los últimos 3 elementos en una lista diferente (no modificar la lista original)

In [6]:
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

ultimos_tres = lst[-3:]

print(ultimos_tres)
print(lst)

[8, 9, 10]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


Ejercicio 3: Dada la siguiente lista, obtener solo los números pares

In [7]:
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

for x in lst:
  if x % 2 == 0:
    print(x)

0
2
4
6
8
10


Ejercicio 4: Dada la siguiente lista, revertir la lista

In [8]:
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
lst_revertido = lst[::-1]
print(lst_revertido)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


Ejercicio 5: Ordenar la siguiente lista de menor a mayor

In [9]:
lst = [4, 1, 6, 12, 3, 2, 1, 7, 1, 0, 14]
lst_ordenado = sorted(lst)
print(lst_ordenado)

[0, 1, 1, 1, 2, 3, 4, 6, 7, 12, 14]


Ejercicio 6: Dada la siguiente lista, seleccionar e imprimir la palabra "Hello"

In [10]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

print(lst[3][1][2][0])

hello


Ejercicio 7: Ordenar la siguiente lista de diccionarios de mayor a menor y de menor a mayor según el valor de 'age'

In [11]:
lst = [
    {
        "name": "A",
        "age": 12
    },
        {
        "name": "B",
        "age": 22
    },
        {
        "name": "C",
        "age": 2
    },
        {
        "name": "D",
        "age": 4
    },
        {
        "name": "E",
        "age": 42
    },
]

lst_ordenado_mayor_a_menor = sorted(lst, key=lambda x: x['age'], reverse=True)
lst_ordenado_menor_a_mayor = sorted(lst, key=lambda x: x['age'])
print(lst_ordenado_mayor_a_menor)
print(lst_ordenado_menor_a_mayor)

[{'name': 'E', 'age': 42}, {'name': 'B', 'age': 22}, {'name': 'A', 'age': 12}, {'name': 'D', 'age': 4}, {'name': 'C', 'age': 2}]
[{'name': 'C', 'age': 2}, {'name': 'D', 'age': 4}, {'name': 'A', 'age': 12}, {'name': 'B', 'age': 22}, {'name': 'E', 'age': 42}]


# Funciones

Ejercicio 1: Crear una función que reciba de entrada un correo electrónico en formato string, y retorne el dominio (lo que va desúes de @)

Entrada: user@domain.com
Salida esperada: domain.com
Usar la expresión lambda para filtrar las palabras que no inicien en s de la siguiente lista

In [12]:
seq = ['soup','dog','salad','cat','great']

get_domain = lambda x: x.split('@')[1]
email = "user@domain.com"
print(get_domain(email))

filter_seq = list(filter(lambda word: word[0].lower() == 's', seq))
print(filter_seq)

domain.com
['soup', 'salad']


Ejercicio 2: Crear una función que reciba 2 parámetros, el primero un frase, y el segundo una palabra (ambos son de tipo string), esta función recisará si la palabra (segundo parámetro) se encuentra en la frase (primer parámetro), solo retornará True o False según el caso.

In [13]:
def contiene_palabra(frase, palabra):
    palabras = frase.split()
    for p in palabras:
        if p.lower() == palabra.lower():
            return True
    return False

frase = "Hola Manu , ¿que tal?"
palabra = "Manu"

print(contiene_palabra(frase, palabra))
palabra = "chocolate"
print(contiene_palabra(frase, palabra))

True
False


Ejercicio 3: Cree una función básica que devuelva True si la palabra 'dog' está contenida en el string dado.

In [14]:
s = "Is there a dog here?"

def contiene_dog(s):
    return 'dog' in s.lower()

print(contiene_dog(s))

s2 = "Is there a cat here?"
print(contiene_dog(s2))

True
False


Ejercicio 4: Cree una función que cuente el número de veces que aparece la palabra "dog" en el string dado

In [15]:
s = "This dog runs faster than the other dog dude!"

def cuenta_dog(s):
    palabras = s.split()
    contador = 0
    for p in palabras:
        if p.lower() == 'dog':
            contador += 1
    return contador

print(cuenta_dog(s))

2


# Numpy Básico

Ejercicio 1: Importa numpy como np

In [ ]:
import numpy as np

Ejericio 2: Crea un arreglo de 10 ceros

In [16]:
import numpy as np

arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Ejercicio 3: Crea un arreglo de 10 unos

In [17]:
import numpy as np

arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Ejercicio 4: Crea un arreglo de 10 cincos

In [18]:
import numpy as np

arr = np.full(10, 5)
print(arr)

arr2 = np.ones(10) * 5
print(arr2)

[5 5 5 5 5 5 5 5 5 5]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Ejercicio 5: Crea un areglo de enteros (int) de 10 a 50

In [19]:
import numpy as np

arr = np.arange(10,51)

print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Ejercicio 6: Crea una matrix de 3x3 con los valores de 0 a 8 -> Revisar método reshape

In [20]:
import numpy as np

matriz = np.arange(9).reshape(3, 3)

print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Ejercicio 7: Crea un arreglo de tamaño 20 lleno de valores aleatorios entre 10 y 100

In [21]:
import numpy as np

arr = np.random.randint(10, 101, size=20)
print(arr)

[28 63 94 66 93 78 83 90 82 16 47 24 83 43 18 43 51 43 58 52]


# Pandas Básico

Ejercicio 1: Importa pandas como pd

In [22]:
import pandas as pd
pd.__version__

'2.2.2'

Ejercicio 2: Leer Salaries.csv como un dataframe y llamarlo sal

In [23]:
sal = pd.read_csv('Salaries.csv')

Ejercicio 3: Revisar el head del dataframe (usar el métdodo head())

In [24]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Ejercicio 4:
¿Cual es el BasePay promedio?

In [25]:
sal["BasePay"].mean()

print("El promedio del BasePay es:", sal["BasePay"].mean())

El promedio del BasePay es: 66325.4488404877


Ejercicio 5: ¿Cuál es la cantidad más alta de OvertimePay en el conjunto de datos?

In [26]:
max_overtime = sal["OvertimePay"].max()
print("La cantidad más alta de OvertimePay es:", max_overtime)

La cantidad más alta de OvertimePay es: 245131.88


Ejercicio 6: ¿Cuál es el cargo de JOSEPH DRISCOLL? Nota: use mayúsculas, de lo contrario, puede obtener una respuesta que no coincida (también hay un Joseph Driscoll en minúsculas)

In [27]:
filtro = sal["EmployeeName"] == "JOSEPH DRISCOLL"
sal[filtro]["JobTitle"]

print("El cargo de JOSEPH DRISCOLL es:", sal[filtro]["JobTitle"].values[0])

El cargo de JOSEPH DRISCOLL es: CAPTAIN, FIRE SUPPRESSION


Ejercicio 7: ¿Cuál es el nombre de la persona mejor pagada (incluidos los beneficios)?

In [28]:
indice_max = sal["TotalPayBenefits"].idxmax()
nombre_max = sal.loc[indice_max, "EmployeeName"]

print("El nombre de la persona mejor pagada es:", nombre_max)

El nombre de la persona mejor pagada es: NATHANIEL FORD


Ejercicio 8: ¿Cuántos títulos de trabajo únicos hay?

In [29]:
titulos_unicos = sal['JobTitle'].nunique()

print(titulos_unicos)

2159


# Bonus

Usando un API construya un programa que muestre la tasa de conversión entre COP y USD, puede usar: Exchange API

Para interactuar con APIs pueden importar esta librería: requests.

In [30]:
import requests

url = "https://api.exchangerate-api.com/v4/latest/COP"

response = requests.get(url)

if response.status_code == 200:
    data = response.json()
    tasa_conversion = data["rates"]["USD"]
    print("La tasa de conversión entre COP y USD es:", tasa_conversion)

La tasa de conversión entre COP y USD es: 0.000244
